version: '3.8'
services:
  MoodGuardian:
    image: 'moodguardian'
    ports:
      - "8080:8080"
    depends_on:
      PostgreSQL:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${PGSQL_URL}/${PGSQL_DB}
      - SPRING_DATASOURCE_USERNAME=${PGSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${PGSQL_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  PostgreSQL:
    image: postgres:15.2-alpine.env
    restart: always
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${PGSQL_PASSWORD}
      - POSTGRES_USER=${PGSQL_USER}
      - POSTGRES_DB=${PGSQL_DB}
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGSQL_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db:
    driver: local